# Generated by Django 6.0.7 on 2026-07-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_image", models.URLField(blank=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("profile_readme", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("account_age", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetricData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("most_used_languages", models.JSONField(default=list)),
                ("merge_rate", models.CharField(blank=True, max_length=255)),
                ("issue_resolution", models.CharField(blank=True, max_length=255)),
                ("pr_resolution", models.CharField(blank=True, max_length=255)),
                ("commit_frequency", models.CharField(blank=True, max_length=255)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="developers.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("readme", "README"),
                            ("dockerfile", "Dockerfile"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="developers.profile",
                    ),
                ),
            ],
        ),
    ]
