# Generated by Django 6.0.7 on 2026-07-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tech_stack",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
